### ISSUE TITLE
refreshrate

### ISSUE THREAD

**Issue by ghost** [UnryzeC/WC3_FPSUnlocker#1]
Возможно отключить принудительную перезапись ключа реестра refreshrate? Мод выставляет 144. Это не всегда соответствует действительности т.к. есть мониторы и побыстрее. И еще написано, что происходит принудительное отключение vsync возможно это тоже не делать? На оба вопроса доводы: я самостоятельно выставляю ключ реестра в зависимости от монитора, ну а отключение vsync в играх неприемлемо в виду разрывов изображения и перегрузки видеокарты.

**Comment by UnryzeC** [comment]
Нет, нельзя. Смысл этой библиотеки в банальном снятии лимита, да и патчи 1.26а и ниже не умеют в в-синк, если не использовать d3d8to9. Добавлять «настройки» = усложнять то, что не предназначено для этого. Для точных настроек есть вфе.

**Comment by ghost** [comment]
Да я не требую настроек, я наоборот спрашиваю можно ли не менять ключ реестра.

**Comment by UnryzeC** [comment]
Его нужно менять, да и оно никому, ничем мешать не может и не должно. Так как банально не отвечает за что-либо. А вот внутренняя часть, которой я устанавливаю лимит фпс для движка игры - другое дело. Но опять же, какой толк эти цифры не менять?

И да, в варкрафте 3 не может быть никаких разрывов без в-синха, в виду локстепа. Так что ещё больше не понимаю недовольства/нужду менять что-либо.

**Comment by ghost** [comment]
Недовольства нет. Возможно я так излагаюсь. Одна благодарность. Ответы понял, все понял, все вопросы сняты. Спасибо!

**Comment by UnryzeC** [comment]
Да не за что, если прямо очень мешает смена ключа/лимита и т.д. я могу быстро сбилдить версию, где в целом будет только снятие внутреннеого лимита без каких-либо изменений герцовки и т.д. Это не сложно, просто немного бесполезно. :P

**Comment by ghost** [comment]
Было бы хорошо, если не сложно. Могут быть ситуации при которых нужно жестко выставить определенную частоту вручную, чтобы она например была 1/2 или 1/4 от максимальной. К примеру есть монитор 240гц и нужно выставить 60 или 120. В текущей ситуации получится 144, ни туда ни сюда. Для меня лучше чтобы была такая возможность сделать это вручную.

**Comment by UnryzeC** [comment]
Это достигается только через V-sync, на патчах 1.26а и ниже - это бесполезно. Но ладно, сейчас соберу, чтобы убедился сам.

**Comment by UnryzeC** [comment]
[FPSUnlocker.zip](https://github.com/UnryzeC/WC3_FPSUnlocker/files/12138931/FPSUnlocker.zip)

**Comment by ghost** [comment]
Спасибо! Это вверх моих желаний! Люблю вручную контролировать такие вещи, даже если они бесполезны))

Нужно больше распространять информацию об этом. Я в паре ресурсов создал темы с ссылками.
