### ISSUE TITLE
1.29 support

### ISSUE THREAD

**Issue by shasen1235** [UnryzeC/WC3_FPSUnlocker#2]
Hello, I came across to find this project and would like to use it.
However, the platform I'm currently play on is using patch 1.29 and the plugin does not work.
Is it possible to add support for 1.29?
Thank you for the hard works!

**Comment by UnryzeC** [comment]
Hello there, sorry for the late reply, issues on github for some reason are not being sent to my email. I am not all that interested in 1.29, but I could add it, though I am not sure what good will it bring as it's a very dead patch.

**Comment by shasen1235** [comment]
Thank you for the reply. I agree that 1.29 is kind of a dead patch, but there's a platfrom in HongKong still has thousands of active users daily. The reason is that 1.29 is like the last patch before moving to reforge and it has native wide screen and relatively modern graphics behaviors compared to 1.28 and below.(For OBS, window minimize...etc)

I can understand your point, just if you can add it, it would benefit thousands. And if you need any assist, I'm willing to help. I'm a WE user as well, just I don't know if this will help any😊

**Comment by UnryzeC** [comment]
The best and only motivation would be a donation, since it's something that I could really care less adding especially on a patch that I have no idea which Chinese platform even uses, I guess KK (former NetEase/Dz or whatever it was).

**Comment by shasen1235** [comment]
That's totally fine, please check your paypal account. Hope a coffee and a beer will motivate you up:D

**Comment by UnryzeC** [comment]
> That's totally fine, please check your paypal account. Hope a coffee and a beer will motivate you up:D

Well, sort of. 1.29c actually introduced more code inlining, so I had to do something that I hate, bytepatching, here is test version:

[FPSUnlocker.zip](https://github.com/user-attachments/files/17451292/FPSUnlocker.zip)

**Comment by shasen1235** [comment]
Thanks man! Let me give it a try when I'm home, will report the result here.

---Edit-------
It works! I can fianlly game on high refresh rate and I cannot express how thankful I'm. 
An additional lunch is on me:D

**Comment by shasen1235** [comment]
Hello again
Sorry I forgot to mention that the file format in the zip is .dll and I need to change to .mix so it will work.
Anything else are working fine so far

**Comment by UnryzeC** [comment]
Yeah, I know, it’s something any user can do themselves, I don’t really remember if I uploaded previous versions as .mix, if so, will update the release to it.
