### ISSUE TITLE
Ломает Alt+Tab с dgVoodoo2

### ISSUE THREAD

**Issue by vlad54rus** [UnryzeC/WC3_FPSUnlocker#3]
По какой то причине использование этого аддона вместе с dgVoodoo2 ломает Alt+Tab в игре - игра не восстанавливается после сворачивания. Пришлось патчить game.dll вручную.
1.26a.

**Comment by UnryzeC** [comment]
Вопросы к dgVoodoo2, данный патч лишь меняет внутренние данные которые отвечают за команду вызова обновления изображения. Ну и в целом такая проблема возможна в виду полноэкранного режима, который сделан через одно место.

Говоря проще, моя библиотека тут не причём.

**Comment by vlad54rus** [comment]
Разобрался в чём проблема. FPSUnlocker форсит параметр refreshrate на 500. После Alt+Tab Warcraft 3 пересоздаёт Swap Chain, в параметрах которого устанавливает частоту обновления в 500 Hz, на что dgVoodoo2 отвечает отказом т.к. видит, что мой монитор не поддерживает такую частоту.
Тут уже вопрос к тебе, [UnryzeC](https://github.com/UnryzeC). Зачем было хардкодить refreshrate в 500? Делать так - неправильно.

P.S. Как временное решение - в настройках dgVoodoo2 можно переопределить используемую частоту обновления, тогда запросы от игры будут проигнорированы.
Запустить dgVoodooCpl.exe, во вкладке General поставить галочку Enumerate refresh rates, далее во вкладке DirectX, в поле Resolution дописать нужную частоту обновления вот в таком виде: `, 60Hz`
